#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

# Battery item with symmetric spacers and bracket styling
sketchybar --add item battery_spacer_right right \
  --set battery_spacer_right \
    background.drawing=off

sketchybar --add item battery right \
  --set battery \
    background.drawing=off \
    icon.drawing=on \
    label.color="$LABEL_COLOR" \
    label.padding_left=0 \
    label.padding_right=0 \
    update_freq=120 \
    script="$PLUGIN_DIR/battery" \
  --subscribe battery system_woke power_source_change

sketchybar --add item battery_spacer_left right \
  --set battery_spacer_left \
    background.drawing=off

sketchybar --add bracket battery_bracket battery_spacer_left battery battery_spacer_right \
  --set battery_bracket \
    background.border_color="$BRACKET_BACKGROUND_BORDER_COLOR" \
    background.color="$BRACKET_BACKGROUND_COLOR" \
    background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
    background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
